Bugfixes & Style changes
RedHatInsights/hooks-frontend pull request #46
Opened 2019-04-24 07:40 UTC by bastilian

2019-04-25 08:57 UTC, bastilian commented
The form is now a bit better strucured with inset event type selection and a bit more room.
![Screenshot_2019-04-25](https://user-images.githubusercontent.com/7757/56723184-c449fc00-6748-11e9-9dcf-824a3f210343.png)

2019-04-25 11:36 UTC, adamruzicka commented on src/SmartComponents/NotificationEdit/NotificationEdit.js
> +    title: 'Basic Details',
Sentence case should be used here

2019-04-25 11:36 UTC, adamruzicka commented on src/SmartComponents/NotificationEdit/NotificationEdit.js
> +                        Triggers
This isn't in the mockups. But it may still be nice to have this as a divider. If we keep it, shouldn't it be some kind of heading?

2019-04-25 11:36 UTC, adamruzicka commented on src/SmartComponents/NotificationsIndex/NotificationsIndex.js
> +                    <ToolbarItem style={ { textAlign: 'right' } }>
The button should be on the left

2019-04-25 12:00 UTC, adamruzicka commented on src/SmartComponents/NotificationEdit/NotificationEdit.js
> +                        Triggers
Also it should probably be hidden if there are no apps

2019-04-25 13:08 UTC, bastilian commented on src/SmartComponents/NotificationEdit/NotificationEdit.js
> +                        Triggers
I think it makes sense to have this or another separator. I added it since the mockup showed `Advasiory - Trigers` as a title with the filter options below. They are now wrapped in titles and looks like this: 
![Screen Shot 2019-04-25 at 15 06 13](https://user-images.githubusercontent.com/7757/56738010-f882e400-676b-11e9-9548-1dacc5e7f795.png)

2019-04-25 14:40 UTC, adamruzicka requested changes
One last thing, then it will be good to go

2019-04-25 14:40 UTC, adamruzicka commented on src/SmartComponents/NotificationEdit/NotificationEdit.js
> +                        loading={ this.props.filterLoading }
We should show the loading state if we're loading filters or apps (or both).

For it to work properly, we need to change `FETCH_APPS` to `pendingMessage(FETCH_APPS)` in https://github.com/RedHatInsights/notifications-frontend/blob/master/src/store/reducers/AppsReducer.js#L16

2019-04-30 14:15 UTC, bastilian commented
@adamruzicka all should be good now. Loading apps or filters now shows a spinner.

2019-04-30 15:04 UTC, adamruzicka approved these changes

2019-04-30 15:04 UTC, merged

2019-04-30 15:05 UTC, adamruzicka commented
Thanks @bastilian ! Looks great