Refactor API error handling
RedHatInsights/hooks-frontend pull request #58
Opened 2019-05-14 14:29 UTC by bastilian

This rewrites the API client to reject a promise in case an error occurs and trigger the notifications middleware, which will look for title and details in the response to show the error.

Requires https://github.com/RedHatInsights/notifications-backend/pull/54 in the backend

2019-05-20 13:17 UTC, adamruzicka requested changes
Works mostly fine when the backend server is up and returning errors.

The only case where it doesn't work are validation errors. Trying to create an endpoint with a name that is already taken fails with just "Error" notification showing up. Also the fields don't get marked as invalid.

If the server is down, just generic errors are shown.

Also an error is shown when you go to endpoint details and it doesn't have a filter assigned. In this case we can safely use empty object as a filter and not show an error

2019-05-20 13:17 UTC, adamruzicka commented on src/SmartComponents/NotificationEdit/NotificationEdit.js
> +            _.forEach(this.props.endpointErrors, (value) => {
When I was testing this, no matter what I tried `this.props.endpointErrors` was always undefined.

2019-05-21 12:33 UTC, bastilian commented
@adamruzicka Mind taking another look.

Validation errors are now passed on correctly and are marking the fields as they should.
There is also now the option to ignore 404 errors for filters to not show an error at all.

When the backend is down the proxy seems to still respond with 200, and and empty response, I'm unsure how to identify those properly as errors with the backend to show a fitting notification.

2019-05-24 10:12 UTC, adamruzicka approved these changes

2019-05-24 10:12 UTC, merged

2019-05-24 10:13 UTC, adamruzicka commented
Thanks @bastilian !