Implement notification filter settings component
RedHatInsights/hooks-frontend pull request #9
Opened 2019-02-27 07:17 UTC by bastilian

2019-02-27 09:13 UTC, adamruzicka reviewed
Left a couple of small comments inline.

2019-02-27 09:13 UTC, adamruzicka commented on src/store/reducers/AppsReducer.js
> +} from './ReducerHelper';
the file is called `reducerHelper`

2019-02-27 09:13 UTC, adamruzicka commented on src/store/reducers/index.js
> +} from './ReducerHelper';
ditto

2019-02-27 09:13 UTC, adamruzicka commented on src/SmartComponents/NotificationEdit/NotificationEdit.js
>          if (id) {
This causes the filter selection component be rendered only if an endpoint is being edited. It would be nice to be able to select them when creating the endpoint.

2019-02-28 09:41 UTC, adamruzicka commented on src/store/reducers/AppsReducer.js
> +    payload.included.filter(item => (item.id === id && item.type === type))[0];
Wouldn't using `find` be better here?

2019-03-01 15:22 UTC, adamruzicka commented on src/SmartComponents/NotificationEdit/NotificationEdit.js
> +        if (this.props.endpoint && this.endpoint.filters && this.endpoint.filters.length > 0) {
`s/this.endpoint/this.props.endpoint/g`

2019-03-04 08:34 UTC, adamruzicka commented on src/store/reducers/AppsReducer.js
> +} from './reducerHelper';
This needs to be imported in the reducer tests too

2019-03-05 16:39 UTC, adamruzicka requested changes
When creating an endpoint, the page gets "redirected" to `/edit` and the event types and friends get unchecked. However, after a proper refresh they appear checked again.

I'm getting the following in the console when going to /edit
![image](https://user-images.githubusercontent.com/7326770/53821208-9a0c6700-3f6d-11e9-8a3e-43bf84d23cbb.png)

Apart from these two and minor inline comments it looks good

2019-03-05 16:39 UTC, adamruzicka commented on src/PresentationalComponents/FilterList/FilterList.js
> +        selectedAppEventTypes: PropTypes.object,
Shouldn't we be describe the shape of it too?

2019-03-05 16:39 UTC, adamruzicka commented on src/PresentationalComponents/FilterList/FilterList.js
> +        this.props.selectedAppEventTypes.eventTypeIds.indexOf(parseInt(eventTypeId)) !== -1;
Could we parse the ids when the data gets loaded and drop the `parseInt` from here?

2019-03-05 16:39 UTC, adamruzicka commented on src/SmartComponents/NotificationEdit/NotificationEdit.js
> +                            <Button variant="secondary">Cancel</Button>
This doesn't seem to do anything

2019-03-05 16:39 UTC, adamruzicka commented on src/SmartComponents/NotificationEdit/NotificationEdit.js
> +    let { filters, loading: filtersLoading } = state.filters;
Does this roughly translate to "Find `loading` in `state.filters` and bind it to a local variable `filtersLoading`"?

2019-03-05 16:39 UTC, adamruzicka commented on src/SmartComponents/NotificationEdit/NotificationEdit.js
> +import FilterList from '../../PresentationalComponents/FilterList/FilterList';
Maybe move this to `src/index.js` and import it from there in the block above?

2019-03-06 08:42 UTC, bastilian commented on src/SmartComponents/NotificationEdit/NotificationEdit.js
> +    let { filters, loading: filtersLoading } = state.filters;
Does exactly that. :) (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Assigning_to_new_variable_names).

2019-03-07 13:11 UTC, adamruzicka commented on src/SmartComponents/NotificationEdit/NotificationEdit.js
> +        this.toIndex();
Shouldn't the redirect be triggered by success of the submit? If I read this right we redirect to index just after submitting the data, without waiting for the result. We may want to stay on the edit page if the saving failed

2019-03-08 12:26 UTC, merged

2019-03-08 12:26 UTC, adamruzicka commented
Thanks @bastilian !